
                    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modallogin"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Criar Login</h3>
				            <h4>Crie um login/senha para continuar usando o Smartpanda sem precisar do Facebook.</h4>
				        </div>
				        <div class="modal-body">
				                <fieldset>
				                    <label>Defina um nome de usuário:</label>
				                    <input type="text" name="frm_login" id="frm_login" maxlength="15" autofocus placeholder="Usuário (Até 15 caracteres)" required>
				                    <label>Defina uma senha</label>
				                    <input type="password" name="frm_senha" id="frm_senha" autofocus placeholder="Senha" required>
				                </fieldset>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
				            <button class="btn btn-primary" onclick="criarLogin();">Enviar</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->

				    
				    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modalcompletarcadastro"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Complete seu cadastro</h3>
				            <h4>Por favor, complete o cadastro para continuar usando o sistema do Smartpanda.</h4>
				        </div>
				        <div class="modal-body">
				                <fieldset>
				                    <label>Razao Social</label>
				                    <input type="text" name="razao_social" id="razao_social" maxlength="100" autofocus placeholder="Razao Social da Empresa" required>
				                    <label>Nome Fantasia</label>
				                    <input type="text" name="nome_fantasia" id="nome_fantasia" maxlength="100" placeholder="Nome Fantasia" value="<?= $this->nome_fantasia ?>" required>
				                    <label>CNPJ</label>
				                    <input type="text" name="cnpj" id="cnpj" maxlength="14" placeholder="CNPJ" required>
				                    <label>Endereço</label>
				                    <input type="text" name="endereco" id="endereco" maxlength="120"placeholder="Endereço da Loja/Shopping" required>
				                    <label>Número</label>
				                    <input type="text" name="nr" id="nr" placeholder="Número" required>
				                    <label>Complemento</label>
				                    <input type="text" name="complemento" id="complemento" maxlength="50" placeholder="Complemento">
				                    <label>CEP</label>
				                    <input type="text" name="cep" id="cep" maxlength="8" placeholder="CEP (somente números)" required>
				                    <label>Email</label>
				                    <input type="text" name="email" id="email" maxlength="255" placeholder="Email" value="<?= $this->email ?>" required>
				                    <label>Telefone</label>
				                    <input type="text" name="telefone" id="telefone" maxlength="15" placeholder="Telefone com DDD" required>
				                </fieldset>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg3" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
				            <button class="btn btn-primary" onclick="completarCadastro();">Enviar</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->

<script><?= $this->script ?></script>