<div class="row">

<!--                     <div class="thumbnail"> -->
                        <!-- <iframe src="<?= $this->webapp ?>" style="width:100%;height:500px;"/> -->
                        <div class="previewQuadro"  style="text-align:center;margin-bottom:20px;">
                        	<h2><?= $this->titulo ?></h2>
                        	<div class="fb-like" data-send="false" data-width="450" data-show-faces="true"></div>
                        	<img src="<?= $this->imagem ?>" alt="Imagem do Anúncio">
                        	
                        	<div style="float:right;margin:35px">
                        		<?= $this->lojistaBanner ?>
                        		<br>
                        		<b><?= $this->lojista ?></b><br><?= $this->shopping ?>
                        	</div>
                        	<br><br>
                        	<p>Para mais informações sobre essa e outras oportunidades acesse o Smartpanda</p>
                        	<p><a href="<?= $this->webapp ?>" title="Abrir no Smartpanda" class="btn btn-success bt-avancar">Abrir no Smartpanda</a></p>
                        </div>
<!--                     </div> -->

            </div>
           

        </div>
        <!-- div container -->