<section id="inner">
<!-- 					<a href="novaoferta" class="btn btn-success bt-avancar">Novo Anúncio</a> -->
                    <?= $this->botao ?>
                    <br />
                    <?= $this->opcoes ?> 
                    <br />
                    <?= $this->msgQtdAnuncios ?>
                    <br />
                    <span id="fimpromocaoMsg" class="label label-attention"><?= $this->msgFimPromocao ?></span>
                    
                    <h2>Anúncios Cadastrados</h2>
                    <?= $this->shoppingFb ?>

                    <table id="tableOfertas" class="table table-hover">

<!--                         Tabela das ofertas -->
                    </table>
                    

					<div id="msgBoxConvite" title="Participar de um Shopping" style="display: none;">
						<fieldset>
							<input type="text" name="inputCodigo" id="inputCodigo" maxlength="8" placeholder="Digite o código de convite">
							<a href="" onclick="event.preventDefault();enviarConvite();" class="btn btn-success bt-avancar">Aceitar Convite</a>
							<p>Obs.: O código de convite é gerado pela administração do Shopping.</p>
						</fieldset>
						<p id="conviteMsg"></p>
					</div>
                    
                    <table id="tableOfertasLojistas" class="table table-hover">

<!--                         Tabela das ofertas dos lojistas -->
                    </table>
                    
                    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modallogin"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Criar Login</h3>
				            <h4>Crie um login/senha para continuar usando o Smartpanda sem precisar do Facebook.</h4>
				        </div>
				        <div class="modal-body">
				                <fieldset>
				                    <label>Defina um nome de usuário:</label>
				                    <input type="text" name="frm_login" id="frm_login" maxlength="15" autofocus placeholder="Usuário (Até 15 caracteres)" required>
				                    <label>Defina uma senha</label>
				                    <input type="password" name="frm_senha" id="frm_senha" autofocus placeholder="Senha" required>
				                </fieldset>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
				            <button class="btn btn-primary" onclick="criarLogin();">Enviar</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->
				    
				    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modalalterarsenha"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Alterar Senha</h3>
				        </div>
				        <div class="modal-body">
				                <fieldset>
				                    <label>Senha Antiga:</label>
				                    <input type="password" name="frm_senhaAntiga" id="frm_senhaAntiga" autofocus placeholder="Senha Antiga" required>
				                    <label>Defina uma nova senha:</label>
				                    <input type="password" name="frm_senhaNova" id="frm_senhaNova" autofocus placeholder="Senha Nova" required>
				                    <input type="password" name="frm_senhaNova2" id="frm_senhaNova2" autofocus placeholder="Digite novamente a senha nova" required>
				                </fieldset>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg2" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
				            <button class="btn btn-primary" onclick="alterarSenha();">Alterar Senha</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->
				    
				    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modalalterarimagens"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Alterar Imagens</h3>
				        </div>
				        <div class="modal-body">
				                <form id="formImagem" enctype="multipart/form-data" action="ofertascadastradas/salvarimagem" method="POST">
				                	<label class="control-label" for="imagem">Imagem do Estabelecimento (Tam. Máximo = 5MB)</label>
				                    <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
				                    <input type="file" id="imagem" name="imagem" required/>
				                    <button type="submit" id="btEnviarImagem" class="btn btn-success bt-avancar">Enviar</button>
				                </form>
				                <? if($this->temImagem) { ?>
				                <br>
				                <form id="formLogo" enctype="multipart/form-data" action="ofertascadastradas/salvarlogo" method="POST">
				                	<label class="control-label" for="imagem">Logo do Estabelecimento (Tam. Máximo = 5MB)</label>
				                    <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
				                    <input type="file" id="logo" name="logo" required/>
				                    <button type="submit" id="btEnviarLogo" class="btn btn-success bt-avancar">Enviar</button>
				                </form>
				                <? } else { ?><p>Após escolher uma imagem, poderá opcionalmente escolher um logo.</p><? } ?>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg2" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->
				    
				    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modalcompletarcadastro"  class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="myModalLabel">Complete seu cadastro</h3>
				            <h4>Por favor, complete o cadastro para continuar usando o sistema do Smartpanda.</h4>
				        </div>
				        <div class="modal-body">
				                <fieldset>
				                    <label>Razao Social</label>
				                    <input type="text" name="razao_social" id="razao_social" maxlength="100" autofocus placeholder="Razao Social da Empresa" required>
				                    <label>Nome Fantasia</label>
				                    <input type="text" name="nome_fantasia" id="nome_fantasia" maxlength="100" placeholder="Nome Fantasia" value="<?= $this->nome_fantasia ?>" required>
				                    <label>Cidade</label>
				                    <select id="cidade" name="cidade" onclick="carregarLojas();"  placeholder="Cidade*" required>
				                    	<option value="1">Salvador</option>
				                    	<option value="2">Lauro de Freitas</option>
				                    </select>
				                    <label>Estabelecimento</label>
				                    <select id="id_estabelecimento" name="id_estabelecimento" required><option>Selecione seu estabelecimento</option></select>
				                    <label>CNPJ</label>
				                    <input type="text" name="cnpj" id="cnpj" maxlength="14" placeholder="CNPJ" required>
				                    <label>Endereço</label>
				                    <input type="text" name="endereco" id="endereco" maxlength="120"placeholder="Endereço da Loja/Shopping" required>
				                    <label>Número</label>
				                    <input type="text" name="nr" id="nr" placeholder="Número" required>
				                    <label>Complemento</label>
				                    <input type="text" name="complemento" id="complemento" maxlength="50" placeholder="Complemento">
				                    <label>CEP</label>
				                    <input type="text" name="cep" id="cep" maxlength="8" placeholder="CEP (somente números)" required>
				                    <label>Email</label>
				                    <input type="text" name="email" id="email" maxlength="255" placeholder="Email" value="<?= $this->email ?>" required>
				                    <label>Telefone</label>
				                    <input type="text" name="telefone" id="telefone" maxlength="15" placeholder="Telefone com DDD" required>
				                </fieldset>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg3" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
				            <button class="btn btn-primary" onclick="completarCadastro();">Enviar</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->
                    
                </div>
                <div class="span5">
<!--                     <h2 id="profile-name"></h2> -->

<!--                     <div class="thumbnail"> -->
<!--                         <img id="profile-pic" src="" alt=""> -->
<!--                     </div> -->

                </div>
            </div>
            <div class="row">

                <div class="offset10 span2">
<!--                     <a href="novaoferta" class="btn btn-success bt-avancar">Nova Oferta</a> -->
                </div>
			</div>
		</section>
        <!-- div container -->
<script><?= $this->script ?></script>