<div class="wrapper">
						<fieldset action="" id="formLogin">
							<h3>Login</h3>
							<input type="text" name="frm_login" id="frm_login" placeholder="Nome de usuário" required> <br>
							<input type="password" name="frm_senha" id="frm_senha"  placeholder="Senha" required> <br>
							<a href="#" class="help-block fz10 link">Esqueceu sua senha?</a>
							<button class="btn btn-info" style="float:left" onclick="enviarLogin()"> <i class="icon icon-lock icon-white"></i> Login</button>
							<button class="btn btn-link fz10" onclick="location.href='http://smartpanda.com.br/promocao01ano'">Cadastre-se</button>
							<br><br>
							<span id="statusMsg" class="label hide"></span>
							<!--<a class="btn-auth btn-facebook" style="margin:0px;margin-top:20px;" href="http://smartpanda.com.br/servidor/loginfb" id="fb_button">
							    Login com <b>Facebook</b>
							</a>-->
						</fieldset>
						<div id="infoLogin">
							<h1>Por que se cadastrar?</h1>
							<div>
								<p> <i class="icon-ok"></i> Aumente suas receitas</p>
								<p> <i class="icon-ok"></i> Gerencie e otimize suas despesas com publicidade</p>
								<p> <i class="icon-ok"></i> Seus produtos e serviços na palma da mão dos<br />&nbsp;&nbsp;&nbsp;&nbsp; consumidores<p>
								<p> <i class="icon-ok"></i> Seja eficaz em satisfazer as necessidades dos seus clientes</p>								
							</div>								
							<div class="ribbon"><div class="ribbon-stitches-top"></div><strong class="ribbon-content"><h1>Promoção um ano pelo preço de um mês!</h1></strong><div class="ribbon-stitches-bottom"></div></div>						
							<button class="btn btn-inverse btn-large" onclick="window.location='http://smartpanda.com.br/promocao01ano'">Saiba mais</button>
							<!-- <button class="btn btn-warning btn-large">Promoção UM ano pelo preço de UM mês</button> -->
						</div>
					</div>
				</div>

<a href="images/banner_modal2.jpg" class="fancybox" id="modalImg" ></a>				
<script type="text/javascript">
	$(document).ready(function() {
		$('#modalImg').fancybox().trigger('click');
    
    $(".fancybox-inner").html('<a href="http://smartpanda.com.br/promocao01ano"> <img class="fancybox-image mostra" src="images/banner_modal2.jpg" alt=""> </a>');
	});
</script>