<div data-role="page" id="detalhes">
		<div data-role="header">
<!-- 			<a href="shoppings" data-role="button" data-icon="home" data-iconpos="notext">Shoppings</a> -->
			<a href="shoppings" data-role="button" data-rel="back" data-icon="back" data-iconpos="notext">Voltar</a>
			<h1 style="margin: .6em 0% .8em;"><img src="img/logo.png" title="Smartpanda" alt="Smartpanda"></h1>
			<a href="#popupMenu" data-rel="popup" data-role="button" data-icon="grid" data-iconpos="notext">Menu</a>
		</div>
		
		<div data-role="content">
		
			<div data-role="popup" id="popupMenu" data-theme="a">
					<ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="b">
						<li data-role="divider" data-theme="a">Menu</li>
						<li><a href="" onclick="event.preventDefault();window.location='./logout';">Sair</a></li>
					</ul>
			</div>
			
			<div data-role="popup" id="popupDialog" data-overlay-theme="a" data-theme="c" style="max-width:370px;" class="ui-corner-all">
				<div data-role="header" data-theme="a" class="ui-corner-top">
					<h1>Opinião Registrada</h1>
				</div>
				<div data-role="content" data-theme="d" class="ui-corner-bottom ui-content">
					<h3 class="ui-title" id="popMsg" style="text-align: center;">Mensagem</h3>
					<p>&nbsp;</p>
					<a href="#" id="btFacebook" onclick="compartilharNoFacebook()" data-role="button" data-rel="back" data-theme="b">Compartilhar no Facebook</a>
					<a href="#" data-role="button" data-rel="back" data-theme="c">Não Compartilhar</a>      
				</div>
			</div>
			
			<div data-role="popup" id="popupInfo3" class="ui-content" data-theme="e" style="max-width:350px;">
          		<p>A internet parece lenta ou não funcional. Tentando conexão novamente...</p>
			</div>
			
			<div data-role="popup" id="popupPicture" class="photopopup" data-overlay-theme="a" data-corners="false" data-tolerance="30,15" >
				<a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Fechar</a><img id="imagemZoom" src="">
			</div>

			<div id="banner"></div><h1 id="lojistaNome" style="font-size:22px;text-align:center;"></h1>
			<script>id_oferta = <?= $this->ofertaID ?>;</script>
			
			<fieldset class="ui-grid-a">
				<div class="ui-block-a" style="position: relative;"><a href="#popupPicture" data-rel="popup" data-position-to="window" data-transition="pop"><img id="imagem" alt="Imagem da Oferta" src="" style="width:90%;height:auto;"/></a><a href="#popupPicture" style="position: absolute;right:10px;" data-rel="popup" data-position-to="window" data-transition="pop" data-role="button" data-icon="plus" class="ui-btn-right" data-iconpos="notext">Ampliar Imagem</a></div>
				<div class="ui-block-b"><h3 id="titulo"></h3></div>
			</fieldset>
			
			<p id="texto"></p>
			
			<div data-role="controlgroup" data-type="horizontal">
				
				
			</div>
			

		</div>
		
		<div data-role="footer" data-position="fixed">		
				<div data-role="navbar">
					<ul>
						<li><a href="#" onclick="event.preventDefault();votarOferta(1)" data-icon="check" data-icon-pos="top"  data-mini="true">Gostei</a></li>
						<li><a href="#" onclick="event.preventDefault();votarOferta(0)" data-icon="minus" data-icon-pos="top"  data-mini="true">Não Gostei</a></li>
					</ul>
				</div><!-- /navbar -->
		</div><!-- /footer -->
</div>