<div class="wrapper">
	<fieldset id="formLogin">
		<h3>Login</h3>
		<input type="text" name="frm_login" id="frm_login" placeholder="Nome de usuário" required> <br>
		<input type="password" name="frm_senha" id="frm_senha"  placeholder="Senha" required> <br>
		<a href="#" class="help-block fz10 link">Esqueceu sua senha?</a>
		<button class="btn btn-info" style="float:left" onclick="enviarLogin();"> <i class="icon icon-lock icon-white"></i> Login</button>
		<button class="btn btn-link fz10" onclick="location.href='../cadastro.php'">Cadastre-se</button>
		<br><br>
		<span id="statusMsg" class="label hide"></span>

		<a class="btn-auth btn-facebook " style="margin:0px;margin-top:20px;" href="http://smartpanda.com.br/servidor/loginfb" id="fb_button">
		    Login com <b>Facebook</b>
		</a>

	</fieldset>

	<div id="infoLogin">
		<h1>Por que se cadastrar?</h1>
		<div>
			<p> <i class="icon-ok"></i> Aumente suas receitas</p>
			<p> <i class="icon-ok"></i> Gerencie e otimize suas despesas com publicidade</p>
			<p> <i class="icon-ok"></i> Seus produtos e serviços na palma da mão dos consumidores</p>
			<p> <i class="icon-ok"></i> Seja eficaz em satisfazer as necessidades dos seus clientes</p>
		</div>
	</div>
</div>