<div class="wrapper">
						<form action="" method="post" id="formCadastro">
							<div id="leftForm" class="less">
								<legend class="titleLegend">Assinante </legend>
								<h5><?= $this->nome ?></h5>
								<h5><?= $this->razao_social ?></h5>						
								
								<br>
									
								<legend class="titleLegend">Plano selecionado</legend>
								<div>
									<label>
										
										<div class="btn-group">
											<button class="btn noCp" onclick="event.preventDefault();">
												<span id="btPlano"><?= $this->planoTitulo ?></span>
											</button>
											<button class="btn btn-info btnH" data-toggle="tooltip" id="changePlan" data-placement="top" data-original-title="Mudar plano" onclick="event.preventDefault();$('#rightForm').fadeIn();"><i class="icon-refresh"></i></button>
										</div>
										<p class="valor">Valor: R$ <span id="valorPlano"><?= $this->planoCusto ?></span>/mês</p> 
									</label>
									<br>
									<div class="btn-group">
										<button class="btn noCp" onclick="event.preventDefault();">Smartpanda TV</button>
									 	<button data-toggle="tooltip" data-placement="top" data-original-title="" value="false" id="change" class="btn btn-danger btnH" ><i class="icon-remove icon-white">&nbsp;</i></button>

									</div>
									<p class="valor">Valor: R$ <span id="valorTv"><?= $this->tvCusto ?></span>/mês	</p>
									
									<legend class="titleLegend">Total Mensal</legend>
									<p>Valor Total: R$ <span id="valorTotal"><?= $this->totalCusto ?></span>/mês	</p>
									<a href="../pagamentos/gerarpagamento"><img style="width:209px;height:48px" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/assinaturas/209x48-assinar-assina.gif" alt="Pague com PagSeguro - é rápido, grátis e seguro!"></a>
								</div>
							</div>

							

							<div id="rightForm" class="larger" style="display:none;">	 <!--  -->
								<legend class="titleLegend">Planos Disponíveis</legend>	
								<table id="tbPlans" class="table" cellpadding="10" cellspacing="0">
									<tr>
										<th>Basic</th>
										<th>Professional</th>
										<th>Premium</th>
										<th>SmartpandaTv</th>
									</tr>
									<tr>
										<td><b>1</b> anúncio por dia + <br /> Relatórios gerenciais</td>
										<td><b>3</b> anúncios por dia + <br /> Relatórios gerenciais</td>
										<td><b>5</b> anúncios por dia + <br /> Relatórios gerenciais</td>
										<td rowspan="2">Tv digital interativa no seu PDV fazendo sua publicidade alternativa</td>
									</tr>
									<tr>
										<td>SmartpandaTV<br /> 0% desconto</td>
										<td>SmartpandaTV<br /> 70% desconto</td>
										<td>SmartpandaTV<br /> <b>100% desconto</b> </td>
										
									</tr>
									<tr>
										<td><p>R$<span id="valorBasic"> 34,90</span>/mês</p> </td>
										<td><p>R$<span id="valorProfessional"> 89,90</span>/mês</p> </td>
										<td><p>R$<span id="valorPremium"> 115,90</span>/mês</p></td>
										<td><p>R$ <span id="valorStv">49,90</span>/mês</p></td>
										
									</tr>
									
									<tr>
										<td colspan="4">
											<button class="btn btn-success btChange" value="1" >Contratar Basic</button>
											<button class="btn btn-success btChange" value="2" >Contratar Professional</button>
											<button class="btn btn-success btChange" value="3" >Contratar Premium</button>
											<button class="btn btn-warning btChange tv" id="btTv" value="4"><i class="icon-white icon-plus"></i> SmartpandaTv</button>	
										</td>
									</tr>
								</table>
							</div>
						</form>
					</div>
					
<script type="text/javascript">
	
	// var plano = [0, "Basic", 89.90, 34.93];

	//atribuindo as variaveis
	var plan = "Basic";
	var desconto = 34.93;
	var valor = 89.90;
	var id = 0;
	var smartpanda = false;
	
	$(document).ready(function(){
		//$("#valorPlano").html(valor.toFixed(2));

		//desconto = 49.9-desconto;
		//$("#valorTv").html(desconto.toFixed(2));
		//var saldo = valor+desconto;
		//$("#valorTotal").append(saldo.toFixed(2));

		//var val = $("#change").attr("value");

		if(val = "false")
			$("#change").attr("data-original-title", "Remover");
		else
			$("#change").attr("data-original-title", "Adicionar");

	});	

	$("button.btChange").click(function(){
		event.preventDefault();
		var value = $(this).attr("value"); 
		
		if(value == 4){
			if($(this).hasClass("btActive")){
				$(this).removeClass("btActive");
				$(this).siblings().attr('disabled', false);
				smartpanda = false;
			}else{
				$(":first-child").attr('disabled', true);
				$(this).addClass("btActive");
				smartpanda = true; //associo smartpanda (4)
			}
			
		}else{

			if(value == 1){
				if($(this).hasClass('btActive')){
					$(this).removeClass('btActive');
					$(this).siblings().attr('disabled', false);
					id = 0;
				}else{
					$(this).addClass('btActive');
					$(this).siblings().attr('disabled', true);
					id = 1;
				}
			}else{

				if($(this).hasClass("btActive")){
					$(this).removeClass("btActive");
					$(this).siblings().attr('disabled', false);
					if($(":nth-child(4)").hasClass('btActive')){
						$(this).siblings("button:not('.btActive')").attr('disabled', false);
						$(":first-child").attr('disabled', true);
					}
					
					id = 0;
					
				}else{
				 	$(this).addClass("btActive");					
				 	$(this).siblings("button:not('.tv')").attr('disabled', true);
					id = $(this).attr('value');
					
				}
			}
		
		}


	});
	

	$("button#change").click(function(){
		event.preventDefault();
		var value = $(this).attr('value');
		

		if(value == "false"){
			$(this).html('<i class=\'icon-plus icon-white\'></i>');
			$(this).removeClass('btn-danger'); 
			$(this).addClass('btn-success');
			$(this).attr("value", "true");
			$(this).attr("data-original-title", "Adicionar");
			return;
		}else{
			$(this).html('<i class=\'icon-remove icon-white\'></i>');
			$(this).removeClass('btn-success'); 
			$(this).addClass('btn-danger');
			$(this).attr("value", "false");
			$(this).attr("data-original-title", "Remover");
			return;
		}


	});
	
	$("#change").tooltip();
	$("#changePlan").tooltip();
	
	

	$("#planos div").click(function(){		
		var value = $(this).find("input").val();	

		if(value != "4"){
			if(value != "smart")
				$("#inputPlano").val(value);

			if(value == "smart")
				$("#inputTv").val("smart");



			if($(this).find("h4").text() != "Smartpanda TV")

				$(this).siblings().removeAttr("style");



			$(this).css("z-index","10");

			$(this).css("box-shadow","0 0 10px #000");



			var smart = $("#inputTv").val();



			if(value == 1 || value == 2 || value == 3)

				$("#assine").delay(300).animate({'opacity':'1'},500);





			if($(this).find("h4").text() == "Professional")
				$("#plano5").find("h3").text("R$ 14,97/mês");
			else if($(this).find("h4").text() == "Premium")
				$("#plano5").find("h3").text("Grátis!");
			else if($(this).find("h4").text() != "Smartpanda TV")
				$("#plano5").find("h3").text("R$ 49,90/mês");

		}

	});

</script>