<div class="wrapper">
	<fieldset id="formLogin">
		<p style="margin-top:50px"><a class="btn-auth btn-facebook " style="margin:0px;margin-top:20px;" href="#" onclick="event.preventDefault();FB.login(function(response) {window.location ='./migrarfb';}, {scope: 'user_birthday'});" class="btn btn-success btn-large">Login via Facebook</a></p>


	</fieldset>

	<div id="infoLogin">
		<h1>Login via Facebook</h1>
		<div>
			<p>O login via Facebook deixará de ser usado.</p>
			<p>Após efetuar o login via Facebook, você será guiado a migrar pro novo sistema.</p>
		</div>
	</div>
</div>