<div class="row">
                <div class="span7">
                    
                    <h2>Lojistas</h2>
                    <p>Créditos Disponíveis: <span id="creditosDisponiveis"></span></p>
					<table id="tableLojistas" class="table table-hover">
						<tr><td>Carregando Dados...</td></tr>
                    </table>
                    
                    <h2 id="h2_convites">Convites para Lojistas</h2>
					<table id="tableConvites" class="table table-hover">
						
                    </table>
                    <a href="shopping/gerarconvite" class="btn btn-success bt-avancar">Gerar Convite de Acesso</a>
                </div>
            </div>


        </div>
        <!-- div container -->