<div data-role="page" id="shoppings">
		<div data-role="header">
			<a href="shoppings" data-role="button" data-rel="back" data-icon="back" data-iconpos="notext">Voltar</a>
			<h1 style="margin: .6em 0% .8em;"><img src="img/logo.png" title="Smarpanda" alt="Smartpanda"></h1>
			<a href="#popupMenu" data-rel="popup" data-role="button" data-icon="grid" data-iconpos="notext">Menu</a>
		</div>
		
		<div data-role="content">
		
			<div data-role="popup" id="popupMenu" data-theme="a">
					<ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="b">
						<li data-role="divider" data-theme="a">Menu</li>
						<li><a href="" onclick="event.preventDefault();window.location='./logout';">Sair</a></li>
					</ul>
			</div>
			
			<div data-role="popup" id="popupInfo1" class="ui-content" data-theme="e" style="max-width:350px;">
          		<p>A internet parece lenta ou não funcional. Tentando conexão novamente...</p>
			</div>

			<script>
				<?= $this->scripts ?>
			</script>
			<p></p>
			<ul data-role="listview" id="listaShoppings">
				<li data-role="list-divider">Shoppings</li>
				
			</ul>
			<br>
			<p id="maisShoppings" style="text-align: center;display:none;"><button onclick="exibirMaisShoppings();">+ shoppings</button></p>

		</div>		
</div>