<div class="row">
                <div class="span7" style="width:100%">
					<select id="estado" name="estado" onclick="listarCidades();"><option>Carregando opções...</option></select>
					<br>
					<select id="cidade" name="cidade" onclick="carregarShoppings();"  placeholder="Cidade*"><option>Selecione um estado primeiro</option></select>
					<br>
					<select id="shopping" name="shopping" onclick="carregarLojas();" required><option>Selecione uma cidade primeiro</option></select>
					
                    <h2>Estabelecimentos</h2>
                    <table id="tableEstabelecimentos" class="table table-hover">
						
                    </table>
				    
				    <!-- -------------------- -->   <!-- Modal -->
				    <div id="modalassinaturas"  class="modal hide fade" style="width:600px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				        <div class="modal-header">
				            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				            <h3 id="precadastro_titulo">Assinaturas</h3>
				        </div>
				        <div class="modal-body">
				        	<div id="lista_assinaturas">

				        	</div>
				        </div>
				        <div class="modal-footer">
				        	<span id="statusMsg" class="label hide"></span>
				            <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
				        </div>
				    </div>
				
				    <!-- -------------------- --> <!-- Modal -->
				    
                </div>
            </div>


        </div>
        <!-- div container -->