<div id="main">
	<h1>Um erro ocorreu :(</h1>
	<h2><?= $this->message ?></h2>
	
	<? if ('development' == $this->env): ?>
		<h3>Informação da Exceção:</h3>
		<p>
			<b>Mensagem:</b> <?= $this->exception->getMessage() ?>
		</p>
		<h3>Rastro da Pilha de Exceções:</h3>
		<pre><?= $this->exception->getTraceAsString() ?></pre>
		<h3>Parâmetros da Requisão:</h3>
		<pre><? var_dump($this->request->getParams()) ?></pre>
	<?php  endif ?>
</div>